import asyncio
import logging
import datetime
import requests
import aiomqtt
import json
from lighting import RoomController, LIVING_ROOM_SCENES
from weather_renderer import render_weather_display
from ble_pusher import fetch_weather, scan_for_tag, TAG_MAC, SCAN_TIMEOUT
from gicisky_ble.writer import update_image

# Restrict logging to errors only to save the RAM disk space
logging.basicConfig(level=logging.ERROR)

# --- CONFIGURATION ---
MQTT_BROKER = "localhost"

living_room_ctrl = RoomController("Living Room", LIVING_ROOM_SCENES)


def _seconds_until_6am() -> float:
    now = datetime.datetime.now()
    target = now.replace(hour=6, minute=0, second=0, microsecond=0)
    if now >= target:
        target += datetime.timedelta(days=1)
    return (target - now).total_seconds()


async def eink_update_loop():
    """Fetches weather and pushes to the e-ink display every day at 06:00."""
    while True:
        wait = _seconds_until_6am()
        logging.info(f"Next e-ink update in {wait / 3600:.1f}h")
        await asyncio.sleep(wait)
        try:
            met_data = fetch_weather()
            image = render_weather_display(met_data)
            ble_device, device_entry = await scan_for_tag(TAG_MAC, SCAN_TIMEOUT)
            if ble_device is None or device_entry is None:
                logging.error("E-ink update: tag not found or not in update mode")
                continue
            success = await update_image(
                ble_device=ble_device,
                device=device_entry,
                image=image,
                threshold=128,
                red_threshold=128,
                attempt=1,
                write_delay_ms=20,
            )
            if not success:
                logging.error("E-ink update: BLE write failed")
        except Exception as e:
            logging.error(f"E-ink update failed: {e}")

async def zigbee_control_loop(client):
    try:
        # Subscribe to all Zigbee devices AND our custom virtual switches
        await client.subscribe("zigbee2mqtt/+")
        await client.subscribe("home/switch/+")
        
        async for message in client.messages:
            topic = str(message.topic)
            payload_str = message.payload.decode().strip()
            
            # 1. Handle incoming JSON from physical Zigbee remotes/switches
            if topic in ["zigbee2mqtt/living_room_remote", "zigbee2mqtt/shelf_switch"]:
                try:
                    payload = json.loads(payload_str)
                    action = payload.get("action")  # Grabs "single", "double", etc.
                    
                    # Xiaomi switches sometimes send an empty action on release.
                    # This line ensures we ignore the blank noise and only act on real clicks!
                    if not action:
                        continue
                        
                except json.JSONDecodeError:
                    continue
            
            # 2. Handle a raw string sent to our virtual python switch topic
            elif topic == "home/switch/living_room":
                action = payload_str
            
            else:
                continue
            
            # Pass the extracted action ("single"/"double") into our room controller
            commands = living_room_ctrl.handle_button_press(action)
            
            # Dispatch all the individual JSON payloads generated by our scenes
            for pub_topic, pub_payload in commands:
                await client.publish(pub_topic, pub_payload)

    except Exception as e:
        logging.error(f"MQTT loop failed: {e}")


async def main():
    # The async context manager automatically handles connections and clean disconnects
    try:
        async with aiomqtt.Client(MQTT_BROKER) as client:
            # Run both the E-ink loop and the MQTT loop concurrently
            await asyncio.gather(
                eink_update_loop(),
                zigbee_control_loop(client)
            )
    except aiomqtt.MqttError as error:
         logging.error(f"MQTT connection error: {error}")

if __name__ == "__main__":
    # Start the async event loop
    asyncio.run(main())
